# Generated by Django 6.0.1 on 2026-01-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cartmodel_cartitemmodels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderItemModels',
        ),
    ]
