# Generated by Django 6.0.1 on 2026-01-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_ordermodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='users',
            new_name='user',
        ),
    ]
